# Site settings
title: KAZUMI'S PORTFOLIO
email: kougi233kazumi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to visit my portfolio.
baseurl:  # the subpath of your site, e.g. /blog/
url:  www.kazumi-lz.com
#twitter_username: twitter_username
#github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
